### PR TITLE
Development2

### LINKED ISSUE #207: Social media profile links and phone numbers are not correct in the team page.
Annotation 2019-10-12 134740

### PR DESCRIPTION
**Pull request by Ankit7Das**
fix #207
corrected facebook links and phone numbers in team.html

### CODE REVIEW

**Comment by atm1504** [comment]
Still wrong. Revert all old commits. https://github.com/Celesta-IITP/Celesta2k19-Webpage/pull/236/commits/1edd51bff2fc5b9e23e9a57d84028da34fc6aba5

**Comment by atm1504** [comment]
@somenath1435 help him with Git commands

**Comment by Ankit7Das** [comment]
Bhaiyya later I made a second PR with development3 branch. There I had updated development from upstream. Development2 did not have the updated development branchOn Oct 15, 2019 4:54 PM, Amartya Mondal <notifications@github.com> wrote:@somenath1435 help him with Git commands

**Comment by atm1504** [comment]
@somenath1435 please look into it.

**Comment by somenath1435** [comment]
@Ankit7Das I can see 3 commits in this pull request...Which ones to keep and which ones to remove?

**Comment by Ankit7Das** [comment]
@somenath1435 bhaiyya the three commits you are seeing are because I didn't update my development before doing the PR. So the first commit was actually for another issue which was closed and later since I was told of my mistake, I made another PR with a different branch (development3 not development2) which if I'm right was merged too. So I think this PR is supposed to be deleted

**Pull request closed without merging**
