### PR TITLE
The Signup link in CA page has been updated

### LINKED ISSUE #233: Link Required in CA.php
The sign up link is missing in the CA.php page

### PR DESCRIPTION
**Pull request by sidpaswan**
fixes #233

### CODE REVIEW

**Comment by sidpaswan** [comment]
please check the second commit the earlier commit had the wrong links

**Comment by atm1504** [comment]
The pr shows too many changes in code other than the ca link. Especially some changes in colors. Add a screenshot of the concern pages.

**Comment by sidpaswan** [comment]
signup_ca1
the pr showed too many colour changes because the color of the ca background had been updated before i submitted my PR by someone else but now i used the original code from the upstream and the background is as same as in the main website

**Comment by sidpaswan** [comment]
signup_ca2
signup_ca3

**Pull request merged**
