### PR TITLE
now all the LOGOS have background

### LINKED ISSUE #241: Change All LOGOS background

### PR DESCRIPTION
**Pull request by sidpaswan**
fixes #241

### CODE REVIEW

**Comment by atm1504** [comment]
Add screenshot to show the changes

**Comment by sidpaswan** [comment]
sponsoors_visible1
sponsoors_visible2

**Comment by sidpaswan** [comment]
i actually replaced 3 images with the edited ones. i hadn't deleted or added something new.

**Comment by sidpaswan** [comment]
you can check it out

**Pull request merged**
